---
# Create Docker config directory
- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'

# Set Docker proxy for University of Melbourne Research Cloud
- name: Ensure Docker client proxy settings are present on the server
  become: yes
  copy:
    content: "{{ docker_proxy_settings }}"
    dest: ~/.docker/config.json

# Build Docker image for web frontend and web backend
- name: Configure compose
  become: yes
  template:
    src: "../template/docker-compose.yaml.j2"
    dest: "/home/ubuntu/COMP90024/ccc-p2/web/docker-compose.yaml"
    owner: "ubuntu"
    group: "ubuntu"

# Run Docker compose to activate web frontend and web backend
- name: Run docker compose
  become: yes
  docker_compose:
    project_src: "/home/ubuntu/COMP90024/ccc-p2/web/"
    pull: false
    build: yes
    state: present
    remove_orphans: no
    recreate: always
